spring:
  application:
    name: distancelearning-authuser-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: distancelearning-config-server
      username: adminconfig
      password: 'adminconfig'
#server:
#  port: 8080
#  servlet:
#    context-path: '/distancelearning-authuser/'
#
#spring:
#  application:
#    name: distancelearning-authuser-service
#  config:
#    import: 'configserver:'
#  cloud:
#    config:
#      discovery:
#        serviceId: distancelearning-config-server
#  datasource:
#    url: jdbc:postgresql://localhost:5432/distancelearning-authuser-v2
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  output:
#    ansi:
#      enabled: Always
#  rabbitmq:
#    addresses: amqps://edchwiwa:PQjjRhmkiBn8wl0J6RFU-z7y7L7Xxs1B@sparrow.rmq.cloudamqp.com/edchwiwa
#
#logging:
#  level:
#    com.distancelearning: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#distancelearning:
#  api:
#    url:
#      course: 'http://distancelearning-course-service/distancelearning-course'
#  broker:
#    exchange:
#      userEvent: distancelearning.userevent
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      circuitbreakerInstance:
#        slidingWindowSize:
#          permittedNumberOfCallsInHalfOpenState: 2
#          slidingWindowType: TIME_BASED
#          minimumNumberOfCalls: 2
#          waitDurationInOpenState: 30s
#          failureRateThreshold: 80
#  retry:
#    instances:
#      retryInstance:
#        maxAttempts: 3
#        waitDuration: 5s