server:
  port: 8081
  servlet:
    context-path: '/distancelearning-course/'

spring:
  application:
    name: distancelearning-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/distancelearning-course-v2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://edchwiwa:PQjjRhmkiBn8wl0J6RFU-z7y7L7Xxs1B@sparrow.rmq.cloudamqp.com/edchwiwa

logging:
  level:
    com.distancelearning: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

distancelearning:
  api:
    url:
      authuser: 'http://distancelearning-authuser-service/distancelearning-authuser'
  broker:
    exchange:
      userEventExchange: distancelearning.userevent
    queue:
      userEventQueue:
        name: distancelearning.userevent.ms.course

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost